### PR TITLE
Add generic container support via gengen

### PR DESCRIPTION
**Pull request by xlab**
I adjusted the types in mailbox to be of type `generic.T` to leverage the https://github.com/joeshaw/gengen package that can produce type-aware code. But the API remains backwards compatible with non-generic approach.

Please see `examples/generic` for illustration of this.
I also adjusted the test, so it won't do typecheck for now, probably need another way to prove correctness of the receive operation (for `interface{}` scenario).

## Generic mailbox benchmark

```
$ go test -benchtime 10s -bench=.
BenchmarkMailbox-4        	100000000	       125 ns/op	       8 B/op	       1 allocs/op
BenchmarkChannel-4        	100000000	       135 ns/op	       8 B/op	       1 allocs/op
BenchmarkBatchMailbox-4   	 1000000	     14671 ns/op	       0 B/op	       0 allocs/op
BenchmarkBatchChannel-4   	  300000	     53762 ns/op	       0 B/op	       0 allocs/op
PASS
```

## Non-generic (`int` type) mailbox benchmark

```
$ cd examples/generic/mailbox_int

$ go test -benchtime 10s -bench=.
BenchmarkMailbox-4        	200000000	        76.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkChannel-4        	100000000	       111 ns/op	       0 B/op	       0 allocs/op
BenchmarkBatchMailbox-4   	 1000000	     14511 ns/op	       0 B/op	       0 allocs/op
BenchmarkBatchChannel-4   	  200000	     56726 ns/op	       0 B/op	       0 allocs/op
PASS
```

### CODE REVIEW

**Comment by xlab** [comment]
I used `-benchtime 10s` because otherwise there is some noise in `BenchmarkMailbox-4`, once time it's 2x faster, another time it's 95% close to built-in channels.

**Comment by itsmontoya** [comment]
You know, the testing inconsistencies worry me a bit. I think it's an issue related to OSX though. I'm not seeing variances at all on my side (Arch Linux). All in all, this pull request was very well done. Thank you for including the before and after benchmarks.

Can we schedule some time to discuss a couple questions I have about the generics?

Hoping to have this merged by EOW (just depends on both of our schedules for communication)

**Comment by itsmontoya** [comment]
Some benchstat comparisons
```
name            old time/op    new time/op    delta
Mailbox-4         86.2ns ± 0%    54.2ns ± 2%   ~             (p=0.100 n=3+3)
BatchMailbox-4    10.4µs ± 0%     9.0µs ± 2%   ~             (p=0.100 n=3+3)

name            old alloc/op   new alloc/op   delta
Mailbox-4          8.00B ± 0%    0.00B ±NaN%   ~             (p=0.100 n=3+3)
BatchMailbox-4    0.00B ±NaN%    0.00B ±NaN%   ~     (all samples are equal)

name            old allocs/op  new allocs/op  delta
Mailbox-4           1.00 ± 0%     0.00 ±NaN%   ~             (p=0.100 n=3+3)
BatchMailbox-4     0.00 ±NaN%     0.00 ±NaN%   ~     (all samples are equal)
```

Hell yea @xlab! :+1:

**Comment by xlab** [comment]
@itsmontoya 
Updated.

**Comment by lucasvmiguel** [comment]
nice work! =)

**Comment by itsmontoya** [comment]
Great work man, approved!

**Pull request merged**
