### PR TITLE
Remove GOTOs and replace with proper flow control.

### PR DESCRIPTION
**Pull request by term1nal**
GOTOs are unnecessary in most contexts in which they're used. I've replaced them with proper flow control.

### CODE REVIEW

**Comment by term1nal** [comment]
I saw the other closed PR where performance dropped with the addition of defer. I tested this against my own changes and saw similar results so I modified it not to use defer and now the performance is very much on par with the pre-PR version.

**Comment by itsmontoya** [comment]
I just merged @xlab's generic generation pull request. Could you please merge against master? Let me know when that's done and we will work towards merging!

Note: I have another branch I'm in the process of merging as well. I may ask you to update once more before we are able to merge, I apologize in advance!

**Comment by term1nal** [comment]
Sure thing.

**Comment by term1nal** [comment]
Closing this PR and opening a new one with #4 changes merged

**Pull request closed without merging**
